project:
  type: website

website:
  title: "Quarto Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - param_quarto.qmd

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
